consultorio/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  devise_for :users, path: '/auth'
  root to:"professionals#index" #ruta de inicio
  resources :professionals do
      resources :appointments do
        collection do
          delete 'cancelall', action: 'cancel_all'
        end
      end
  end
  get '/grids/new', to: 'grids#new'

  post '/grids', to: 'grids#to_export'

  #get 'profile', action: :new, controller: 'grids'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

consultorio/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
          :rememberable, :validatable
  validates :role, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, uniqueness: false

  enum role: [:query, :assistance, :administrator]
end

consultorio/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  #before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :role)
    end
end

consultorio/app/helpers/users_helper.rb
module UsersHelper
end

consultorio/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :role %>
    
    <%= form.select :role, User.roles.keys, selected:user.role%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

consultorio/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

consultorio/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', professionals_path %>
<h1>Users</h1>

<table >
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <% if can? :read, User %>
          <td><%= link_to 'Show', user %>
        <% end %>
        <% if can? :write, User %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :write, User %>
<%= link_to 'New User', new_user_path %>
<% end %>

consultorio/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

consultorio/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>