consultorio/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  devise_for :users, path: '/auth'
  root to:"professionals#index" #ruta de inicio
  resources :professionals do
      resources :appointments do
        collection do
          delete 'cancelall', action: 'cancel_all'
        end
      end
  end
  get '/grids/new', to: 'grids#new'

  post '/grids', to: 'grids#to_export'

  #get 'profile', action: :new, controller: 'grids'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

consultorio/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional
  validates :date, presence: true,uniqueness: { scope: [:professional_id] }
  validates :name, presence: true
  validates :surname, presence:true
  validates :phone, presence:true
  validates :notes, presence:false, length: { maximum: 50 }

  validate  :is_sunday?, :valid_time?,   :valid_date?
  scope :by_date, ->(date) { where("strftime('%Y-%m-%d', date) IN (?)", Array(date)) }
  def is_sunday?
    if self.date.sunday?
      errors.add :date, "Professionals don't work on Sundays, please request another day"
  
    end
  end

  def self.schedule
    @schedule ||= begin
        schedule=[]
        (10..20).each do |hs|
            schedule.push("#{hs}:00")
            schedule.push("#{hs}:30")
        end
        schedule
      end
  end
  def valid_time?
    
    if not Appointment.schedule.include?(self.date.strftime('%H:%M')) 
      errors.add :date, "The appointment could not be created. The hours allowed to take appointments are between 10:00 and 20:30 and only in the minutes: 00 and 30. For example: 11:30"
    end
  end 

  def valid_date?
    begin
      DateTime.strptime(self.date.to_s,  '%Y-%m-%d %H:%M:%S')
    rescue => exception
      errors.add :date, "The date format is invalid"
    end
    
  end

end

consultorio/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource :professional
  load_and_authorize_resource :appointment, through: :professional

  # GET /appointments
  def index
   
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create

    if @appointment.save
      redirect_to [@professional, @appointment] , notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /appointments/1
  def update
    if @appointment.update(appointment_params)
      redirect_to [@professional, @appointment], notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    redirect_to  professional_appointments_url(@professional), notice: 'Appointment was successfully destroyed.'
  end

  def cancel_all
    @professional.appointments.destroy_all
    redirect_to  professional_appointments_url(@professional), notice: 'Appointments were successfully destroyed.'
  end

  private


    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :name, :surname, :phone, :notes)
    end
end

consultorio/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

consultorio/app/views/appointments/_form.html.erb
<%= form_with(model: [@professional,appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

consultorio/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<%= link_to 'Show', [@professional, @appointment] %> |
<%= link_to 'Back', professional_appointments_path(@professional) %>

consultorio/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>
<%= link_to 'Back', professionals_path %><br>
<% if not @appointments.any? %>
  <i>There are not appointments yet</i>
<%else%>
<table>
  <thead>
    <tr>
      <th>Date</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <% if can? :read, appointment %>
          <td><%= link_to 'Show', [@professional, appointment] %></td>
        <% end %>
        <% if can? :write, appointment %>
          <td><%= link_to 'Edit', edit_professional_appointment_path(@professional,appointment) %></td>
          <td><%= link_to 'Cancel', [@professional, appointment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :write, Appointment %>
  <td><%= link_to 'Cancel all', cancelall_professional_appointments_path(@professional), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
<%end%>
<br>
<% if can? :write, Appointment %>
  <%= link_to 'New Appointment', new_professional_appointment_path(@professional) %>
<% end %>

consultorio/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', professional_appointments_path(@professional) %>

consultorio/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<%= link_to 'Edit', edit_professional_appointment_path(@professional,@appointment) %> |
<%= link_to 'Back', professional_appointments_path(@professional) %>