consultorio/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  devise_for :users, path: '/auth'
  root to:"professionals#index" #ruta de inicio
  resources :professionals do
      resources :appointments do
        collection do
          delete 'cancelall', action: 'cancel_all'
        end
      end
  end
  get '/grids/new', to: 'grids#new'

  post '/grids', to: 'grids#to_export'

  #get 'profile', action: :new, controller: 'grids'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

consultorio/app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments, dependent: :restrict_with_error
    validates :name, presence: true, uniqueness: true

end

consultorio/app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  load_and_authorize_resource
  #before_action :set_professional, only: [:show, :edit, :update, :destroy]

  # GET /professionals
  def index
    @professionals = Professional.all
  end

  # GET /professionals/1
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals
  def create
    @professional = Professional.new(professional_params)

    if @professional.save
      redirect_to @professional, notice: 'Professional was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /professionals/1
  def update
    if @professional.update(professional_params)
      redirect_to @professional, notice: 'Professional was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /professionals/1
  def destroy
    if @professional.destroy
      redirect_to professionals_url, notice: 'Professional was successfully destroyed.'
    else
      #tengo que avisar que no puede
      redirect_to professionals_url, alert: "The professional could not be destroyed because he/she has appointments."
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:name)
    end
end

consultorio/app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

consultorio/app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

consultorio/app/views/professionals/edit.html.erb
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

consultorio/app/views/professionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professionals</h1>
<% if not @professionals.any? %>
  <i>There are not professionals yet</i>
<%else%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.name %></td>
        <% if can? :read, professional %>
          <td><%= link_to 'Show', professional %></td>
        <%end%>
        <% if can? :write, professional %>
          <td><%= link_to 'Edit', edit_professional_path(professional) %></td>
          <td><%= link_to 'Destroy', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <% if can? :read, professional %>
          <td><%= link_to 'Appointments', professional_appointments_path(professional) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<% if can? :write, Professional %>
  <%= link_to 'New Professional', new_professional_path %>
<% end %>
<% if can? :write, User %>
  <%= link_to 'See users', users_path %>
<% end %>
<%= link_to 'Download information', grids_new_path %>

consultorio/app/views/professionals/new.html.erb
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

consultorio/app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>

<%= link_to 'Edit', edit_professional_path(@professional) %> |
<%= link_to 'Back', professionals_path %>